version: "3.9"

services:

  postgres_db:
    image: postgres
    command: postgres -c 'max_connections=10000'
    ports:
      - "5435:5432"
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}


#  djangobackend:
#    image: djangoms-image
#    ports:
#      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
#    volumes:
#      - ./app
#    entrypoint:
#      - /entrypoint.sh
#      #- python3 manage.py test
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_NAME=${DB_NAME}
#      - DB_USER=${DB_USER}
#      - DB_PASS=${DB_PASS}
#    depends_on:
#      - postgres_db
