version: "3.9"

services:

  postgres_db:
    image: postgres
    command: postgres -c 'max_connections=10000'
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}


  djangobackend:
    image: manga-image
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    volumes:
      - ./ecommerce:/app/ecommerce  # Mount only the ecommerce directory
      - ./manage.py:/app/manage.py    # Mount manage.py directly
      - ./requirements.txt:/app/requirements.txt  # Mount requirements.txt directly
#      - ./entrypoint.sh:/entrypoint.sh
      - ./media:/app/media
      - ./static:/app/static
    entrypoint:
      - /entrypoint.sh
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - RDB_HOST=${RDB_HOST}
      - RDB_NAME=${RDB_NAME}
      - RDB_USER=${RDB_USER}
      - RDB_PASS=${RDB_PASS}
      - RDB_PORT=${RDB_PORT}
      - USE_S3=${USE_S3}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    depends_on:
      - postgres_db
