# Generated by Django 3.2.19 on 2023-06-26 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecommerce.account.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abstract', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('intentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstract.intentity')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان 2')),
                ('phone_number_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الهاتف 1')),
                ('phone_number_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الهاتف 2')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='تأريخ الميلاد')),
                ('province', models.CharField(blank=True, choices=[('بغداد', 'بغداد'), ('البصرة', 'البصرة'), ('نينوى', 'نينوى'), ('ميسان', 'ميسان'), ('ذي قار', 'ذي قار'), ('المثنى', 'المثنى'), ('القادسية', 'القادسية'), ('النجف', 'النجف'), ('كربلاء', 'كربلاء'), ('واسط', 'واسط'), ('الأنبار', 'الأنبار'), ('ديالى', 'ديالى'), ('صلاح الدين', 'صلاح الدين'), ('السليمانية', 'السليمانية'), ('دهوك', 'دهوك'), ('أربيل', 'أربيل'), ('بابل', 'بابل'), ('كركوك', 'كركوك')], max_length=255, null=True, verbose_name='المحافظة')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'المستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            bases=('abstract.intentity', models.Model),
            managers=[
                ('objects', ecommerce.account.models.CustomUserManager()),
            ],
        ),
    ]
