# Generated by Django 3.2.19 on 2023-08-04 18:39

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors')),
                ('born_location', models.CharField(blank=True, max_length=100, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('شونن', 'Shonen'), ('شوجو', 'Shoujo'), ('سينين', 'Seinen'), ('جوسي', 'Josei'), ('ايسيكاي', 'Isekai'), ('الخيال', 'Fantasy'), ('الرومانسية', 'Romance'), ('الكوميديا', 'Comedy'), ('شريحة من الحياة', 'Slice of Life'), ('الميكا', 'Mecha'), ('الرعب', 'Horror'), ('الرياضة', 'Sports')], default='شونن', max_length=100), size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.author')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('IQD', 'Iraqi Dinar'), ('USD', 'US Dollar')], default='IQD', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('8000'), default_currency='IQD', max_digits=14)),
                ('image', models.ImageField(blank=True, null=True, upload_to='volumes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_chapter', models.IntegerField(blank=True, null=True)),
                ('end_chapter', models.IntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Volumes',
            },
        ),
    ]
