# Generated by Django 3.2.19 on 2023-09-01 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='pages',
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='demographics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('شونن', 'Shonen'), ('كودومو', 'Kodomo'), ('سينين', 'Seinen'), ('شوجو', 'Shoujo'), ('جوسي', 'Josei'), ('سيجين', 'Seijin'), ('ريديسو', 'Redisu'), ('جيكيجا', 'Gekiga'), ('ايسيكاي', 'Isekai'), ('الرومانسية', 'Romance'), ('الكوميديا', 'Comedy'), ('شريحة من الحياة', 'Slice of Life'), ('الميكا', 'Mecha'), ('الرعب', 'Horror'), ('الرياضة', 'Sports'), ('شوتا', 'Shota')], max_length=100, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('شونن', 'Shonen'), ('كودومو', 'Kodomo'), ('سينين', 'Seinen'), ('شوجو', 'Shoujo'), ('جوسي', 'Josei'), ('سيجين', 'Seijin'), ('ريديسو', 'Redisu'), ('جيكيجا', 'Gekiga'), ('ايسيكاي', 'Isekai'), ('الرومانسية', 'Romance'), ('الكوميديا', 'Comedy'), ('شريحة من الحياة', 'Slice of Life'), ('الميكا', 'Mecha'), ('الرعب', 'Horror'), ('الرياضة', 'Sports'), ('شوتا', 'Shota')], max_length=100, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('شونن', 'Shonen'), ('كودومو', 'Kodomo'), ('سينين', 'Seinen'), ('شوجو', 'Shoujo'), ('جوسي', 'Josei'), ('سيجين', 'Seijin'), ('ريديسو', 'Redisu'), ('جيكيجا', 'Gekiga'), ('ايسيكاي', 'Isekai'), ('الرومانسية', 'Romance'), ('الكوميديا', 'Comedy'), ('شريحة من الحياة', 'Slice of Life'), ('الميكا', 'Mecha'), ('الرعب', 'Horror'), ('الرياضة', 'Sports'), ('شوتا', 'Shota')], max_length=100, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='title_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_japanese',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('مانجا', 'Manga'), ('رواية خفيفة', 'Light Novel'), ('مانهوا', 'Manhwa'), ('كوميك', 'Comic')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volumes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
