# Generated by Django 3.2.19 on 2023-09-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='product.Author'),
        ),
    ]
