# Generated by Django 3.2.19 on 2023-09-01 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230901_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_japanese',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='volume',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
