# Generated by Django 3.2.19 on 2023-09-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20230901_1524'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='author',
            index_together={('name', 'role')},
        ),
    ]
