# Generated by Django 3.2.19 on 2023-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_author_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='author',
            index_together=set(),
        ),
    ]
