# Generated by Django 3.2.19 on 2023-09-05 14:27

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_author_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('8000'), default_currency='IQD', max_digits=14),
        ),
    ]
