# Generated by Django 3.2.19 on 2023-09-05 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_volume_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='demographics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('الأطفال', 'Kids'), ('شوجو', 'Shoujo'), ('شونين', 'Shounen'), ('سينين', 'Seinen'), ('جوسي', 'Josei')], max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('فائز بجوائز', 'Award Winning'), ('الأكشن', 'Action'), ('الرومانسية', 'Romance'), ('الكوميديا', 'Comedy'), ('الرعب', 'Horror'), ('الغموض', 'Mystery'), ('الخارق', 'Supernatural'), ('شريحة من الحياة', 'Slice of Life'), ('الذوق الرفيع', 'Gourmet'), ('الخيال العلمي', 'Sci-Fi'), ('الرياضة', 'Sports'), ('الخيال', 'Fantasy'), ('المغامرة', 'Adventure'), ('التشويق والإثارة', 'Suspense'), ('الدراما', 'Drama')], max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('ماهو شوجو', 'Mahou Shoujo'), ('الساموراي', 'Samurai'), ('ايسيكاي', 'Isekai'), ('القوى الخارقة', 'Super Power'), ('التنكر', 'Crossdressing'), ('تعليمي', 'Educational'), ('الميكا', 'Mecha'), ('السخرية', 'Parody'), ('التناسخ', 'Reincarnation'), ('لعبة استراتيجية', 'Strategy Game'), ('اياشيكي', 'Iyashikei'), ('نفسي', 'Psychological'), ('الجريمة المنظمة', 'Organized Crime'), ('سباق', 'Racing'), ('السفر عبر الزمن', 'Time Travel'), ('الفضاء', 'Space'), ('مكان العمل', 'Workplace'), ('المحقق', 'Detective'), ('صناعة الترفيه', 'Showbiz'), ('الفنون البصرية', 'Visual Arts'), ('متجسد', 'Anthropomorphic'), ('نكتة فكاهية', 'Gag Humor'), ('الشريرة', 'Villainess'), ('ثقافة أوتاكو', 'Otaku Culture'), ('حريم', 'Harem'), ('الفنون القتالية', 'Martial Arts'), ('النص الرومانسي الفرعي', 'Romantic Subtext'), ('الحيوانات الأليفة', 'Pets'), ('لعبة فيديو', 'Video Game'), ('البقاء على قيد الحياة', 'Survival'), ('CGDCT', 'CGDCT'), ('المدرسة', 'School'), ('تاريخي', 'Historical'), ('طبي', 'Medical'), ('مصاص الدماء', 'Vampire'), ('المارقون', 'Delinquents'), ('العسكري', 'Military'), ('الموسيقى', 'Music'), ('فريق الكبار', 'Adult Cast'), ('رعاية الأطفال', 'Childcare'), ('العنف الدموي', 'Gore'), ('الأساطير', 'Mythology'), ('رياضات القتال', 'Combat Sports'), ('حريم معكوس', 'Reverse Harem'), ('الفنون الأدائية', 'Performing Arts'), ('مذكرات', 'Memoir'), ('رياضات الفريق', 'Team Sports'), ('مضلع الحب', 'Love Polygon'), ('لعبة المخاطر العالية', 'High Stakes Game')], max_length=100, null=True), default=list, size=None),
        ),
    ]
