# Generated by Django 3.2.19 on 2023-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20230905_1803'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name', 'role'], name='product_aut_name_073276_idx'),
        ),
    ]
