# Generated by Django 3.2.19 on 2023-09-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_author_product_aut_name_073276_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
