# Generated by Django 3.2.19 on 2023-09-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
