# Generated by Django 3.2.19 on 2023-09-15 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20230908_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='demographics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('كودومو', 'Kids'), ('شوجو', 'Shoujo'), ('SHOUNEN', 'شونين'), ('سينين', 'Seinen'), ('جوسي', 'Josei')], max_length=100, null=True), default=list, size=None),
        ),
    ]
