# Generated by Django 3.2.19 on 2023-09-17 08:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_nav_ad_active'),
        ('product', '0016_alter_product_demographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
            ],
            options={
                'verbose_name': 'product_banner',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.admodel',),
        ),
        migrations.AlterField(
            model_name='product',
            name='demographics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('كودومو', 'Kids'), ('شوجو', 'Shoujo'), ('شونين', 'Shounen'), ('سينين', 'Seinen'), ('جوسي', 'Josei')], max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='volume',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume', to='product.product'),
        ),
    ]
