# Generated by Django 3.2.19 on 2023-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='images/ad/')),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AModel',
            fields=[
            ],
            options={
                'verbose_name': 'Why us',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.admodel',),
        ),
        migrations.CreateModel(
            name='BModel',
            fields=[
            ],
            options={
                'verbose_name': 'Big Ad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.admodel',),
        ),
        migrations.CreateModel(
            name='CModel',
            fields=[
            ],
            options={
                'verbose_name': 'Small Ad 1',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.admodel',),
        ),
        migrations.CreateModel(
            name='DModel',
            fields=[
            ],
            options={
                'verbose_name': 'Small Ad 2',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.admodel',),
        ),
    ]
