# Generated by Django 3.2.19 on 2023-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230728_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admodel',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
