# Generated by Django 3.2.19 on 2023-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230728_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admodel',
            options={'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterField(
            model_name='admodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='admodel',
            unique_together={('type', 'active')},
        ),
    ]
