# Generated by Django 3.2.19 on 2023-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230728_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='admodel',
            name='prompt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
