# Generated by Django 3.2.19 on 2023-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_admodel_prompt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='nav_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
