# Generated by Django 3.2.19 on 2023-08-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nav_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav_ad',
            name='active',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
